/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10/userguide/building_java_projects.html in the Gradle documentation.
 */

// Константы для версий зависимостей.
object Versions {
    const val SPRING_BOOT = "3.3.4"
    const val JAVA = "21"
    const val LOMBOK = "1.18.34"
    const val JACKSON_DATABIND = "2.18.0-rc1"
    const val SLF4J_API = "1.7.30"
    const val LOGBACK_CLASSIC = "1.4.12"
    const val LOGBACK_CORE = "1.4.14"
    const val LIQUIBASE_CORE = "4.29.2"
    const val POSTGRESQL = "42.7.4"
    const val SPRING_BOOT_STARTER_SECURITY = "3.3.5"
    const val JJWT_API = "0.12.6"
    const val JJWT_IMPL = "0.12.6"
    const val JJWT_JACKSON = "0.12.6"
}

// Константы для библиотек.
object Libraries {
    const val SPRING_FRAMEWORK_BOOT = "org.springframework.boot"
    const val LOMBOK = "org.projectlombok:lombok:${Versions.LOMBOK}"
    const val JACKSON_DATABIND = "com.fasterxml.jackson.core:jackson-databind:${Versions.JACKSON_DATABIND}"
    const val SLF4J_API = "org.slf4j:slf4j-api:${Versions.SLF4J_API}"
    const val LOGBACK_CLASSIC = "ch.qos.logback:logback-classic:${Versions.LOGBACK_CLASSIC}"
    const val LOGBACK_CORE = "ch.qos.logback:logback-core:${Versions.LOGBACK_CORE}"
    const val SPRING_BOOT_STARTER_WEB = "org.springframework.boot:spring-boot-starter-web:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_VALIDATION =
        "org.springframework.boot:spring-boot-starter-validation:${Versions.SPRING_BOOT}"
    const val LIQUIBASE_CORE = "org.liquibase:liquibase-core:${Versions.LIQUIBASE_CORE}"
    const val POSTGRESQL = "org.postgresql:postgresql:${Versions.POSTGRESQL}"
    const val SPRING_BOOT_STARTER_SECURITY =
        "org.springframework.boot:spring-boot-starter-security:${Versions.SPRING_BOOT_STARTER_SECURITY}"
    const val JJWT_API = "io.jsonwebtoken:jjwt-api:${Versions.JJWT_API}"
    const val JJWT_IMPL = "io.jsonwebtoken:jjwt-impl:${Versions.JJWT_IMPL}"
    const val JJWT_JACKSON = "io.jsonwebtoken:jjwt-jackson:${Versions.JJWT_JACKSON}"
}

plugins {
    application
    id("org.springframework.boot") version "3.3.4"
}

repositories {
    // Используем Maven Central для разрешения зависимостей.
    mavenCentral()
}

dependencies {
    // Lombok
    implementation(Libraries.LOMBOK)
    annotationProcessor(Libraries.LOMBOK)

    // Jackson
    implementation(Libraries.JACKSON_DATABIND)

    // SLF4J и Logback для логирования.
    implementation(Libraries.SLF4J_API)
    implementation(Libraries.LOGBACK_CLASSIC)
    implementation(Libraries.LOGBACK_CORE)

    // Spring Boot Starter Web
    implementation(Libraries.SPRING_BOOT_STARTER_WEB)
    // Spring Boot Starter Validation
    implementation(Libraries.SPRING_BOOT_STARTER_VALIDATION)
    // Liquibase
    implementation(Libraries.LIQUIBASE_CORE)
    // PostgreSQL
    implementation(Libraries.POSTGRESQL)

    // Spring Boot Starter Security
    //implementation(Libraries.SPRING_BOOT_STARTER_SECURITY)
    // JJWT для работы с JWT токенами.
    //implementation(Libraries.JJWT_API)
    //implementation(Libraries.JJWT_IMPL)
    //implementation(Libraries.JJWT_JACKSON)
}

// Настройка Java toolchain для использования конкретной версии Java.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(Versions.JAVA)
    }
}

// Добавление параметра -parameters для поддержки именованных параметров в Lombok.
tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("-parameters")
}

// Настройка тестов для использования JUnit Platform.
tasks.named<Test>("test") {
    useJUnitPlatform()
}
