server:
  port: ${PORT:8080}

spring:
  application:
    name: t-invest-tracker

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    driver-class-name: org.postgresql.Driver
    change-log: migrations/changelog-master.xml

  jackson:
    time-zone: Europe/Samara

  jooq:
    sql-dialect: Postgres

springdoc:
  server-url:
    - http://localhost:8080

invest:
  token: ${INVEST_TOKEN}

resilience4j:
  ratelimiter:
    instances:
      forecastRateLimiter:
        limitForPeriod: 190
        limitRefreshPeriod: 1m
        timeoutDuration: 5s

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
