version: '3.8'

services:
  db:
    image: postgres:17
    container_name: t-invest-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 3s
      timeout: 5s
    volumes:
      - /var/lib/postgresql/data
    networks:
      - app-tier

  t-invest:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: t-invest
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      INVEST_TOKEN: ${INVEST_TOKEN}
    ports:
      - "8080:8080"
    networks:
      - app-tier

  frontend:
    build:
      context: ../invest-frontend
    container_name: invest-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../invest-frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    depends_on:
      - db
      - t-invest
    stdin_open: true
    tty: true
    networks:
      - app-tier

networks:
  app-tier:
    name: app-tier
    driver: bridge